### ISSUE TITLE
Possible quick fix for large pdf files (using electron)

### ISSUE THREAD

**Issue by LeanderFlamm** [elyukai/optolith-client#1094]
The pdf files of the character sheet generated by electron are really big, especially when using the background and a char image. This could also be a cause of #812 .

Even though a rework of the pdf generation seems to be planned long-term, I maybe found the cause of this behaviour. Chromium is re-rendering all images that are cropped via CSS before saving them, resulting in large and sometimes still blurry images. This can be evaded by using a parent element to mask the image instead of cropping the image itself. Details are given here: [github.com PDF file too large](https://github.com/puppeteer/puppeteer/issues/458#issuecomment-711167965).

As I have not worked with js before, I thought I'd rather post my findings than fiddling with the code myself (for now).

**Comment by elyukai** [comment]
This is great! :o I will try that! Thanks so much für letting me know! 😍🥰🤗

Yeah, they *are* really big, since it also seems like it duplicates the image for every page even though its always the same image. And, well, a custom PDF generation is still quite a bit away, since doing that via HTML/CSS is just so different from imperatively creating PDF contents step by step … 🙃🙄🙈

**Comment by elyukai** [comment]
I do have to say that I just tried the given solution and its still over 30 MB. 😭 So, yeah, I'll probably keep the changes so that it may be refined later, but I don't know how to continue on this issue at this point. 😕

**Comment by LeanderFlamm** [comment]
Ah that's sad 😢. From your code I cannot see what's wrong, but I would have to try it for myself. I have two more ideas:

- Maybe try to save Character-Sheet-Background as jpg instead of png? Even with high quality (95%) I got the file size to 979 KB with no obvious fragments. In the linked issue they were using jpgs I think.
- I tried to compress a character sheet pdf with an external tool (pdf24) with great success: it went down to 500 KB. It could be possible to do some post-processing with a pdf library to get the same effect. Still, this would not decrease processing times and the freezing issue.

Good luck and thanks for trying anyways!

**Comment by elyukai** [comment]
- I tried to keep it as PNG to have proper resolution if you would want to print this (its also 300ppi because of this). But I can try it with JPG and maybe offer the option to switch between "display quality" and "print quality". 🤔 
- Would need to see if there is a package for Node. Which probably is. I always try to minimize dependencies, though, thats why I'm gonna try to do it without.

Thank *you* for all your help regarding this issue! :o

It would be just so cool to have a library for creating PDFs in a declarative way. Now that there is so much for declarative UI definitions this would be a huge benefit. 😭🙈 (I consider this export via HTML more like a workaround than a proper implementation, at least the Chromium implementation, which is not really reliable considered changes made to @page rules and that stuff. Needed to reduce the height of the page so that it doesnt overflow, even with A4 setting &ndash; A4 needing to be smaller than A4 to fit on A4 doesn't really make sense to me.)

**Comment by JoveToo** [comment]
I do not see the same problems you do. If I export my character as pdf it is 570kb, including a portrait image, which seems reasonable to me? I am using Optolith on Linux though. 

If I run the pdf  through ghostscript, 

> gs  -sDEVICE=pdfwrite  -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH -sOutputFile=test.pdf character.pdf

it reduces it further to 330Kb.

**Comment by elyukai** [comment]
Do you also use the paper background?

**Comment by JoveToo** [comment]
Wow. With paper background generation takes forever, almost 30 seconds, while without is instantaneous.

And yes, with paper background it is also 34MB. 
If I run it through ghostscript, it is 1.3MB

**Comment by elyukai** [comment]
Yes, this is really not cool, although compression seems to be a nice way. But I cant do anything to reduce the generation time except probably reduce the background file format/size/quality.

**Comment by JoveToo** [comment]
Why would generating a pdf with a background image take so long? It doesn't actually have to render anything?

I always turn off that image when i print anyway, only very, very expensive printers can print to the edge of the page and the white border around it makes it look ugly.

I see the source file for the background is 6.4MB, at 5 times that would get you 34MB. It could probably be compressed considerably without losing any visible quality.

**Comment by elyukai** [comment]
I have no idea. I only use the HTML to PDF renderer from Chromium and there are no other settings available, at least considering what Electron exposes.

I don't use it too but it seemed like there were quite a few people interested in this. And for digital use its quite nice. But I dont know if it is *only* used for digital use, thats why I kept the background image in printing quality. But, yeah, I could provide a JPG version with 72ppi for display use (or maybe 150ppi for HiDPI displays), this should reduce the size significantly.

Its quite annoying that Chromium considers mutliple instances of the same image in the exact same sizes as different "files" to include.

**Comment by LeanderFlamm** [comment]
For me it's only digital use, yes, as we are doing our sessions online at the moment anyway. To print it, I use the pdf without background, too.

**Comment by elyukai** [comment]
Ok, JPG with 150ppi results in 1.42 MB for a sheet without portrait. That seems to be fine IMO.
