### ISSUE TITLE
Name of tradition "Scharlatane" does not conform to naming convention

### ISSUE THREAD

**Issue by BlueSkyBlackBird** [elyukai/optolith-client#1239]
**Describe the bug**
The name of the Tradition "Scharlatan" is currently written as singular. This does not conform to the de facto standard of traditions which is `tradition (*pluralizedName*)`. A problem arises when you want to know (for a spell) what traditions can learn it and try to use that pattern to create the correct tradition. 

**To Reproduce**
See the latest version of optolith-data on DEV.

**Expected behavior**
Name should be plural.
```
- id: SA_676
  name: "Tradition (Scharlatane)"
```

**Screenshots**
```
- id: SA_676
  name: "Tradition (Scharlatan)"
```

**Environment (please complete the following information):**
iirelevant

**Additional context**
none

**Comment by elyukai** [comment]
The string resources for the tradition SA and it's string in the spellworks' tradition lists are different things. The latter ones are stored in `Data/<lang>/MagicalTraditions.yaml` files. Concerning the singular vs. plural, based on the older books and their revisions I would say that they started TDE5 using singular and then at some point decided it would make more sense to use the plural form. This happened definitely after Magic I since there they still use the singular form (at least in the version I own) and this is also why I kept the singular form for traditions that have not been revised yet. If that happened and I was just blind, I'll need to change it! 😅 But otherwise I'd leave it as it is since no other string is going to be derived from it.
