### ISSUE TITLE
AMA2: New Cultures (Koboldweltler & Steppenelfen)

### ISSUE THREAD

**Issue by Raphael-Thelen** [elyukai/optolith-client#1372]
## Sources

> List here what is included in this part of the book to implement. E.g., for special abilities, you need to list every source of entries from the book. Example (in German):
> - S. 227-228 (Kulturen)

**Comment by elyukai** [comment]
Thank you for you request! 

AMA2 is fully implemented, which includes both cultures. Are you missing them in the application? Please make sure to

- activate the ruleset for AMA2 and 
- set the culture filter option to "All cultures" instead of "Common cultures".

Does the problem still exist? Do you have a different problem?

Thanks!

**Comment by Raphael-Thelen** [comment]
Sorry about the confusion, i did not realize, that a different elvish subspecies needs to be choosen, as Steppenelfen are only a culture and not a species technically. Thats just the rules i guess.
I have found it now and will be closing the issue. Thank you!

**Comment by elyukai** [comment]
No worries! There are *some* things in the Core Rules that don't really work if you use advanced rule books as well …

I just try to stay as close to the rules as possible and thus be "neutral" concerning the ruleset. TDE5 is certainly not meant to be used in applications in the first place. 🙃🙈
