### ISSUE TITLE
Unable to add the profession "Eulenhexer (Verschwiegene Schwesterschaft)"

### ISSUE THREAD

**Issue by modomiro** [elyukai/optolith-client#1584]
### Please confirm the following

- [X] I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.

### Describe the bug

No matter which Culture I choose, there is no profession for the Eulenhexer showing. 

### To Reproduce

1. Held erstellen: m/w, erfahren, alle Regelwerke
2. Spezies: Mensch
3. Kultur: egal welche
4. Profession: Nirgendwo wird Eulenhexer angezeigt

### Expected behavior

I don't see a reason why there is no possibility to choose the profession Eulenhexe. (Vgl. Aventurische Magie 2, S. 186, S. 204f.)

### Operating System

macOS

### Version

1.5.1, 1.5.2

**Comment by elyukai** [comment]
Which profession filters (in the left sidebar) are active? Try to deactivate “Common Professions” and choose “All Professions”. Does that fix the issue?

Background: Professions from books except the Core Rules are usually not counted as common professions, since they could not have been taken into account when the list of common profession was created. This is not the case for cultures of advanced books, but they are usually very specific about its common professions.

**Comment by modomiro** [comment]
Thank you! That did the trick ... my fault, I am sorry!

**Comment by elyukai** [comment]
No worries! You’re definitely not the only one having problems with this! I really need to improve the user experience there – and in quite a few other areas as well … Sorry about the confusion!
