### ISSUE TITLE
Better way to display already included values

### ISSUE THREAD

**Issue by Kallimeister** [elyukai/optolith-client#1589]
For some values it's not exactly clear if values like burden are already included in calculation (f.e. speed) or not. So maybe a little explanation or calculation way on the sheet how a value is calculated would clarify that.

**Comment by elyukai** [comment]
The derived characteristics – and other values – should be "final" by default. At least what can be "statically" determined.

The only exception are the combat values on the combat sheet, which is a temporary problem I hope to be able to address soon.

Which "value group" is unclear for you? If I forgot to include certain entries in the calculations, I will fix it!

**Comment by Kallimeister** [comment]
Sorry for the late response. Busy times ;)
Especially recuring uncertanties whiole playing are values influenced by burden:
Ausweichen/ Parade, Geschwindigkeit, Initative, Attacke
Are burden steps by armor and/ or inventory already included or have to be subtracted additionally? And what about SFs like Belastungsgewöhnung?
Change of the way armor is shown on the inventory sheet, so it doesn't add additionaly to the burden through its weight.
Maybe a little field on the Inventory sheet (and in the inventory tab in Optolith) for showing influences on and calculating burden would be a nice addition.

**Comment by elyukai** [comment]
Those should be fixed with #59. Since that feature will just included everything that's possible – excluding only values that are “ephemeral”, that is, bonuses or penalties by maneuvers. The current handling is not intuitive, I know, and once item sets are available, I will probably disable it, so you have to use item sets in any case to get calculated values.

So, this will include *Inured to Encumbrance* (Belastungsgewöhnung), not including *equipped* armor into Encumbrance calculation for carrying capacity, and applying the total encumbrance to all combat-related values (AT, PA, INI, MOV etc.).

The remaining question is: Would that solve your problem completely? Or are there still things that are not handled?

**Comment by Kallimeister** [comment]
I think that will solve it.
