### ISSUE TITLE
Cannot open App in MacOS 14.0 because of Security issues

### ISSUE THREAD

**Issue by skranz0** [elyukai/optolith-client#1625]
### Please confirm the following

- [X] I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.

### Describe the bug

After downloading the .dmg and moving the app in my applications folder, I cannot use Optolith since MacOS complains the developer could not be verified and thus blocks the app to protect me from malware.

### To Reproduce

1. Download the Optolith 1.5.1
2. Move file to applications folder
3. Start app from Launchpad

### Expected behavior

The app should start

### Screenshots

<img width="409" alt="Bildschirmfoto 2023-11-09 um 15 10 56" src="https://github.com/elyukai/optolith-client/assets/61312852/ae681cfd-8379-41f1-b715-41f69cb5de3f">

### Operating System

macOS

### Version

1.5.1

**Comment by elyukai** [comment]
First of all: Thank you for your report!

This is a known issue with older versions, since I didn't have an Apple Developer license back then. The current prereleases are signed and notarized, and so are future stable releases.

As a workaround, you can open the Settings app, section Privacy & Security, and almost at the bottom you can manually allow running Optolith.

I cannot sign and notarize an existing stable version, and porting everything back and doing builds in general is quite time-consuming, even with a CI/CD workflow, since DriveThru has no API and I'm currently working on quite a diverged version for a future MAJOR release, so I don't want to spent more time on the V1 unless absolutely necessary, because I don't have that much spare time right now.

So it's basically fixed, but only for prereleases and future V2 versions.

**Comment by skranz0** [comment]
The 1.5.2 alpha works, thanks!

Sadly, the Apple Developer license is quite expensive, if I heard correctly. The workaround does not work in newer macOS releases, though. You can only choose between *allow only from App Store* and *allow from App Store and signed developers*.

Completely understandable, you don't want to go back through basically deprecated releases. A hint only >= 1.5.2 will work on macOS >= 14.0 would be useful, I think.

**Comment by elyukai** [comment]
You’re welcome!

It’s €99 per year, so … yeah, quite a bit. But it’s currently funded via my Patreon for Optolith, so at least that works now.

> A hint only >= 1.5.2 will work on macOS >= 14.0 would be useful, I think.
I just wasn’t aware of the stricter handling on Sonoma, I’m afraid. I do try to not miss any changes that affect Optolith from WWDC, but that slipped through, apparently. Gonna catch up on that. Thanks for pointing that out!

**Comment by elyukai** [comment]
Did you try to open Optolith **while** having that page of the Settings app open?

**Comment by skranz0** [comment]
You were right, if I have the Security Setting open at the same time a prompt to add an exception appears. Only for a short time though. Basically impossible to guess for an end user.

**Comment by elyukai** [comment]
Ah okay, yeah, then nothing changed with Sonoma. But yeah, it's basically impossible to guess. I may add a line to the Scriptorium page.
