### ISSUE TITLE
Firungeweihter profession missing

### ISSUE THREAD

**Issue by Flohs** [elyukai/optolith-client#1628]
### Please confirm the following

- [X] I checked the [current issues](https://github.com/elyukai/optolith-client/issues) for duplicate problems.

### Describe the bug

No matter what species and culture I chose, I was not able to pick Firungweihter as profession.

### To Reproduce

1. Create a new character
2. Choose random name and gender
3. Select Average experience 1000 AP
4. Select all Rule books
5. In the character editor select species "Human"
6. Culture Fjarniger
7. Go to professions and try to search for Firungeweihter

In this screenshot I filtered for all professions, sorted by alphabet and scrollt to the end of the professions starting with the letter "E".
<img width="1134" alt="Bildschirmfoto 2024-06-01 um 18 40 30" src="https://github.com/elyukai/optolith-client/assets/4445415/ca566956-cf19-42ff-bf1d-eb16341d4c3e">

### Expected behavior

Firungeweihter should show up as profession.

### Operating System

macOS

### Version

1.5.1

**Comment by pickbreaker** [comment]
That is indeed correct. You can't create a blessed one of firun on experience level average because the profession includes a combat technique at level 12, but the maximum level for combat techniques for experience level average is 10. Optolith enforces this and prevents you from breaking said rule.

**Comment by Flohs** [comment]
Thank you very much for clarifying.
