### ISSUE TITLE
Optional paper-style background for character sheet

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#36]

**Comment by Rahjenaos** [comment]
what style are we looking for? 
One perfectly fitting (DIN A4?) image or rather something repeatable like this:
![image](https://user-images.githubusercontent.com/4533505/84660805-ad9cd080-af19-11ea-807b-cd78598597c5.png)


How should it be selectable?
Maybe with a checkbox "Parchment instead of white background" right below the "Show attribute values" on the left side of the character sheet?
