### ISSUE TITLE
AMA3: Druid wizardy styles (Zauberstile) don't get pulled when profession is selected

### ISSUE THREAD

**Issue by Fletcher0306** [elyukai/optolith-client#362]
For witches, Wizards and elves the wizardy style is selected automatically when a Profession is selected, for Druids this is not. This behaviour is inconsistent.

Either it isn't selected at all or for all the cases. I do prefer that is isn't selected in case that the Player is not using the wizardy style Focus rule.

**Comment by elyukai** [comment]
It depends on the profession you select. Every profession package reflects *exactly* the entry from the books – that’s also why there are sometimes two professions with the same name: Different values. But changing a profession package would lead to mismatches between Optolith and the source.

If there are Spell Style Special Abilities included in a Druid profession package in the book but it’s not in the profession package in Optolith, please reopen this issue, in that case it is a bug, otherwise it is intended.
