### ISSUE TITLE
Autoupdater fails for Version 1.03. with an error occured during auto-update. code:2, domain:SQRLUpdaterErrorDomain on OSX

### ISSUE THREAD

**Issue by pk2061** [elyukai/optolith-client#547]
**Describe the bug**
Autoupdater fails for Version 1.03. with: "An error occured during auto-update. code:2, domain:SQRLUpdaterErrorDomain"

I am running MacOSX 10.14

**To Reproduce**

1. Open Settings
2. Click on "CHECK FOR UPDATES" 
3. Click on "UPDATE"

-> After downloading the files the error message occurs.
`An error occured during auto-update. ({"code":2,"domain":"SQRLUpdaterErrorDomain"})`

**Expected behavior**
I expect the updater to install the version 1.03.

**Environment (please complete the following information):**

- OS: MacOSX 10.14.6
- Version: 1.0.2

**Comment by elyukai** [comment]
Even though this is a very old issue, to finally answer this one: Auto-updates are currently disabled on macOS, since I have neither a Mac nor a (paid) Apple Developer Account, which I need to code sign the update files, which is required for the auto-updates to work. So this is "kind of" working as intended. IIRC the button is disabled on macOS as well as the initial check on start-up.
