### ISSUE TITLE
Disadvantage Principles: Wrong calculation if selected twice

### ISSUE THREAD

**Issue by Fletcher0306** [elyukai/optolith-client#551]
**Describe the bug**
If the disadvantage "Prinzipientreue" is selected twice on point number is added and the other one is deducted. Correct would be that just the point for the higher one is added and the other one not considered-.

**To Reproduce**
Create a new character
Add disadvantage "Prinzipientreue" at level 2
Look at the adventure points added. Should be 20.
Add disadvantage "Prinzipientreue" at level 1
Look at the advanture points added. The points for the first disadvantage will be 10. For the second one 0.

Correct: 20 Adventure points added for character creation should have been added for the higher one instead of 10.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- OS: [e.g. Windows 10]
- Version: 1.4.0-alpha.5

**Additional context**

**Comment by JoveToo** [comment]
Confirmed. This does happen but it is a display bug only. The calculated AP of the character are correct.

**Comment by JoveToo** [comment]
Ok, this is not so simple as it appears.
The displayed AP is the AP you get when you remove the entry.
So if you have a Principle II (-20AP by itself) and a Principle I (-10 AP by itself) and you remove the P II, you only get -10AP (because then the PI becomes worth -10 AP) and you get 0 AP when removing the P I. 
So the values displayed by the tool are correct but not all that intuitive.

**Comment by elyukai** [comment]
Working as intended, see #372 for more details.
