### ISSUE TITLE
Saving a single hero disables save buttons of other heroes as well

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#811]
> Something I noticed, if you have multiple heroes that have been edited and you click "save" on one of them, all the save buttons grey out. I don't know if they are actually saved or not.

— **Jove** on Discord

**Comment by rasmusgrote** [comment]
I was not able to reproduce that error - I was able to save all my characters seperately (using win 10 and Optolith version 1.4.2) maybe it is only on an specific device?

**Comment by JoveToo** [comment]
To be clear, this happens when you are looking at your characters in the main character list. If you go into a character and modify it and come out of it, only the save button of that character is enabled. If you do that with two characters and then click save on one of them, both are greyed out.
This is on Linux, 1.4.2

**Comment by rasmusgrote** [comment]
Yes, I did exactly that. So maybe this in an Issue only on linux?

**Comment by pickbreaker** [comment]
Can confirm with following Versions:

- 1.4.2 on Windows
- 1.4.3-alpha.1 on Windows
- 1.4.2 AppImage on Ubuntu
- 1.4.3-alpha.1 on Ubuntu

**Comment by JonasTrampe** [comment]
Confirmed for 1.5.0-alpha.4 on Windows
